 routes:
   -
     name: streamx-web-route
     id: web-server
     uri: /*
     hosts:
       - web.127.0.0.1.nip.io
     upstream:
       nodes:
         "web-server.webserver:80": 1
       type: roundrobin
     plugins:
       gzip:
         buffers:
           number: 8
         types: "*"
   -
     name: streamx-search-route
     id: search-engine
     uri: /search/*
     hosts:
       - web.127.0.0.1.nip.io
     upstream:
       nodes:
         "search-engine:8080": 1
       type: roundrobin
   -
     name: streamx-ingestion-route
     id: rest-ingestion
     uri: /*
     hosts:
       - ingestion.127.0.0.1.nip.io
     upstream:
       nodes:
         "rest-ingestion:8080": 1
       type: roundrobin
 #END
